id: translator
name: "翻譯工具"
version: "1.0.0"
description: "提供文字翻譯功能的 MCP Server"
type: mcp-server
transport: stdio
command: python
args: ["server.py"]
env:
  OPENAI_API_KEY: "${OPENAI_API_KEY}"
auto_start: false
dependencies:
  - openai
  - mcp
tags:
  - translation
  - utility
